# Database Connection Properties
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://sql12.freesqldatabase.com:3306/sql12832751?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.username=sql12832751
db.password=pPtJIpdsJm
