# Database Connection Properties
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
db.username=postgres.wrzgzswlpblqvcjrbunn
db.password=Praveen@2005<>
