-- ==========================================================
-- Sample data for Smart Inventory - 30 Products
-- ==========================================================

INSERT INTO products (sku, name, description, category, price, stock_quantity, min_stock_level, expiry_date, supplier_id) VALUES
('SKU001', 'Organic Apples (1kg)', 'Crisp organic red apples.', 'Fresh Produce', 150.00, 20, 5, DATE_ADD(CURDATE(), INTERVAL 10 DAY), 1),
('SKU002', 'Whole Milk (1L)', 'Full-fat pasteurized cow milk.', 'Dairy & Eggs', 60.00, 3, 5, DATE_ADD(CURDATE(), INTERVAL 6 DAY), 2),
('SKU003', 'Brown Eggs (12pk)', 'Free-range large brown eggs.', 'Dairy & Eggs', 120.00, 35, 10, DATE_ADD(CURDATE(), INTERVAL 15 DAY), 2),
('SKU004', 'Chicken Breast (1kg)', 'Fresh boneless chicken breast.', 'Meat & Seafood', 350.00, 15, 8, DATE_ADD(CURDATE(), INTERVAL 4 DAY), 1),
('SKU005', 'Fresh Salmon (500g)', 'Wild caught Atlantic salmon fillet.', 'Meat & Seafood', 500.00, 1, 5, DATE_ADD(CURDATE(), INTERVAL 2 DAY), 1),
('SKU006', 'Sourdough Bread', 'Freshly baked artisanal sourdough loaf.', 'Bakery & Bread', 90.00, 12, 5, DATE_ADD(CURDATE(), INTERVAL 3 DAY), 2),
('SKU007', 'Butter Croissants (4pk)', 'Flaky, buttery bakery croissants.', 'Bakery & Bread', 110.00, 2, 5, DATE_SUB(CURDATE(), INTERVAL 2 DAY), 2),
('SKU008', 'Coca-Cola (1.25L)', 'Classic carbonated soft drink.', 'Beverages', 45.00, 50, 15, NULL, 3),
('SKU009', 'Sparkling Water (500ml)', 'Carbonated natural spring water.', 'Beverages', 25.00, 10, 20, NULL, 3),
('SKU010', 'Dark Chocolate (100g)', '70% cocoa rich dark chocolate bar.', 'Snacks & Confectionery', 80.00, 45, 10, DATE_ADD(CURDATE(), INTERVAL 180 DAY), 3),
('SKU011', 'Potato Chips (150g)', 'Classic salted crispy potato chips.', 'Snacks & Confectionery', 50.00, 60, 15, DATE_ADD(CURDATE(), INTERVAL 90 DAY), 3),
('SKU012', 'Frozen Peas (500g)', 'Sweet green peas, IQF frozen.', 'Frozen Foods', 75.00, 25, 8, DATE_ADD(CURDATE(), INTERVAL 120 DAY), 3),
('SKU013', 'Frozen Pepperoni Pizza', 'Wood-fired stone baked pepperoni pizza.', 'Frozen Foods', 220.00, 4, 10, DATE_ADD(CURDATE(), INTERVAL 60 DAY), 3),
('SKU014', 'Canned Tomato Paste', 'Double concentrated rich tomato paste.', 'Canned & Packaged', 40.00, 80, 20, DATE_ADD(CURDATE(), INTERVAL 365 DAY), 3),
('SKU015', 'Canned Tuna in Oil', 'Premium solid light tuna in sunflower oil.', 'Canned & Packaged', 95.00, 120, 30, DATE_ADD(CURDATE(), INTERVAL 500 DAY), 3),
('SKU016', 'Basmati Rice (1kg)', 'Aged long-grain aromatic basmati rice.', 'Grains & Pulses', 110.00, 40, 10, NULL, 3),
('SKU017', 'Red Lentils (1kg)', 'Split red lentils, high in protein.', 'Grains & Pulses', 85.00, 3, 10, NULL, 3),
('SKU018', 'Dishwashing Liquid', 'Lemon fresh grease cutting dish soap.', 'Cleaning & Household', 120.00, 30, 8, NULL, 3),
('SKU019', 'Laundry Detergent (1L)', 'Concentrated liquid laundry detergent.', 'Cleaning & Household', 250.00, 15, 5, NULL, 3),
('SKU020', 'Herbal Shampoo (400ml)', 'Nourishing aloe vera shampoo.', 'Personal Care', 180.00, 20, 5, NULL, 3),
('SKU021', 'Mint Toothpaste (150g)', 'Fluoride toothpaste for fresh breath.', 'Personal Care', 65.00, 0, 10, NULL, 3),
('SKU022', 'Baby Wipes (80pk)', 'Fragrance-free sensitive baby wipes.', 'Baby Products', 110.00, 35, 10, NULL, 3),
('SKU023', 'Baby Diapers (Large)', 'Ultra-absorbent comfortable baby diapers.', 'Baby Products', 600.00, 8, 15, NULL, 3),
('SKU024', 'Bananas (1 Dozen)', 'Fresh yellow sweet bananas.', 'Fresh Produce', 60.00, 18, 5, DATE_ADD(CURDATE(), INTERVAL 5 DAY), 1),
('SKU025', 'Greek Yogurt (500g)', 'Thick and creamy unsweetened Greek yogurt.', 'Dairy & Eggs', 140.00, 8, 10, DATE_SUB(CURDATE(), INTERVAL 1 DAY), 2),
('SKU026', 'Apple Juice (1L)', '100% pure unsweetened apple juice.', 'Beverages', 90.00, 22, 10, DATE_ADD(CURDATE(), INTERVAL 15 DAY), 3),
('SKU027', 'Chocolate Chip Cookies', 'Freshly baked soft-baked cookies.', 'Snacks & Confectionery', 120.00, 5, 5, DATE_SUB(CURDATE(), INTERVAL 5 DAY), 2),
('SKU028', 'Multi-Surface Cleaner', 'Lavender scent disinfecting spray.', 'Cleaning & Household', 150.00, 14, 5, NULL, 3),
('SKU029', 'Baby Lotion (200ml)', 'Gentle moisturizing baby lotion.', 'Baby Products', 175.00, 12, 5, NULL, 3),
('SKU030', 'Whole Wheat Bread', 'Freshly baked healthy whole wheat bread loaf.', 'Bakery & Bread', 45.00, 15, 5, DATE_ADD(CURDATE(), INTERVAL 2 DAY), 2);
